Repository ProyectoIntegrador2018/EEMI_IOS, pull requests merged in 2019-02, with the labels that each got.

#3 adds api documentation
  endpoints.md
  readme.md
Labels: enhancement

#5 Launch screen
  EEMI/EEMI/Base.lproj/LaunchScreen.storyboard
Labels: enhancement, sprint 1

#6 Refactor appointments
  EEMI/EEMI/ApiClient.swift
  EEMI/EEMI/Appointment.swift
Labels: sprint 1

#2 Settings
  EEMI/EEMI/Assets.xcassets/forward_arrow.imageset/Contents.json
  EEMI/EEMI/Assets.xcassets/forward_arrow.imageset/forward_arrow.png
  EEMI/EEMI/Assets.xcassets/lock.imageset/Contents.json
  EEMI/EEMI/Assets.xcassets/lock.imageset/lock.png
  EEMI/EEMI/Base.lproj/Main.storyboard
  EEMI/EEMI/DateExtension.swift
Labels: sprint 1, user story
